### ISSUE TITLE
HAP Warning

### ISSUE THREAD

**Issue by nik0dim** [bstuff/haier-ac-remote#5]
Hello! Everything was fine and everything worked, but something broke and I can’t do anything about it.
HAP Warning: Characteristic 000000B6-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HELP PLEASE

**Comment by bstuff** [comment]
Feel free to make PR

**Comment by nik0dim** [comment]
I do not understand, sorry. before the plugin worked and now it gives an error
[2020-5-21 14:54:43] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[2020-5-21 14:54:43] [Config] [HapClient] [192.168.1.11:51869 (0E:88:6E:7B:04:88)] Failed to set value for Fan speed.

**Comment by nik0dim** [comment]
You can help?

**Comment by bstuff** [comment]
HAP Warning will be fixed in #6.
ECONNRESET is a different issue related to `haier-ac-remote` lib. It can be fixed independently.
If someone will send a pull request, I'll be glad to merge it.
